name: "Functional Friday"
highlighter: pygments
exclude: [README.md, LICENSE, Makefile]
baseurl: /functional-friday
permalink: :year-:month-:day-:title

markdown: kramdown
markdown_ext: md

# Information for the Atom feed
gereksiz:
   author: "Jeremy Hughes"
   email: "jedahu@gmail.com"