name: "Functional Friday"
markdown: redcarpet
highlighter: pygments
exclude: [README.md, LICENSE, Makefile]
baseurl: /functional-friday

# Information for the Atom feed
gereksiz:
   author: "Jeremy Hughes"
   email: "jedahu@gmail.com"
