name: "Functional Friday"
markdown: kramdown
highlighter: pygments
exclude: [README.md, LICENSE, Makefile]
baseurl: /functional-friday
permalink: :year-:month-:day-:title

# Information for the Atom feed
gereksiz:
   author: "Jeremy Hughes"
   email: "jedahu@gmail.com"

kramdown:
    use_coderay: true